"use strict";
let num1 = "18";
let result = num1;
console.log(result);
let num2 = 18;
let result1 = num2;
console.log(result1);
let num3 = "18";
let result3 = num3;
console.log(result3);
let num4 = 18;
let result4 = num4;
console.log(result4);
